services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - SPREADSHEET_NAME=${SPREADSHEET_NAME}
      - SHARE_TO_EMAIL=${SHARE_TO_EMAIL}
    tty: true  # Allocate a pseudo-TTY
    stdin_open: true  # Keep stdin open to allow interactive input
