services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - SPREADSHEET_NAME=${SPREADSHEET_NAME}
      - SHARE_TO_EMAIL=${SHARE_TO_EMAIL}
    ports:
      - "4000:80"  # Expose port 80 in the container and map it to port 4000 on the host
