services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "4000:80"  # Expose port 80 in the container and map it to port 4000 on the host
